### ISSUE TITLE
Events periodically cause a daemon failure

### ISSUE THREAD

**Issue by aphlor** [kounch/homebridge-avea-bulb#2]
Super good plugin, hadn't spotted that nodejs had any modules for bluetooth access. Props 👍 

Unfortunately, I have a small issue with homekit eagerly hitting homebridge with lots of state changes within a small period.

Infrequent on/off and colour changes are fine, but if a large volume of requests come in, it seems that something occurs causing an uncaught exception.

```
[8/10/2017, 12:31:29 AM] [Office Lamp] setHue from/to: 253 250
[8/10/2017, 12:31:29 AM] [Office Lamp] setSaturation from/to: 100 100
[8/10/2017, 12:31:29 AM] [Office Lamp] setHue from/to: 250 247
[8/10/2017, 12:31:30 AM] [Office Lamp] setSaturation from/to: 100 100
[8/10/2017, 12:31:30 AM] [Office Lamp] setHue from/to: 247 247
[8/10/2017, 12:31:31 AM] [Office Lamp] setSaturation from/to: 100 100
/usr/local/node-v6.11.1-linux-armv6l/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
throw new Error("This callback function has already been called by someone else; it can only be called one time.");
^
Error: This callback function has already been called by someone else; it can only be called one time.
at /usr/local/node-v6.11.1-linux-armv6l/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
at Object.setSaturation (/usr/local/node-v6.11.1-linux-armv6l/lib/node_modules/homebridge-avea-bulb/index.js:413:13)
at emitMany (events.js:127:13)
at emit (events.js:201:7)
at Characteristic.setValue (/usr/local/node-v6.11.1-linux-armv6l/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
at Bridge.<anonymous> (/usr/local/node-v6.11.1-linux-armv6l/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:733:22)
at Array.forEach (native)
at Bridge.Accessory._handleSetCharacteristics (/usr/local/node-v6.11.1-linux-armv6l/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:678:8)
at emitMany (events.js:127:13)
at HAPServer.emit (events.js:201:7)
```

If I had to guess, perhaps a bluetooth request has been sent out before the previous one had been complete. But that's a guess, I've not looked at the code yet.

It's late, so I'm logging this but I'll try and spend some time looking at this over the weekend.

**Comment by kounch** [comment]
I think the problem could be here:

            this.log("setSaturation from/to:", this.Saturation, value);
            var oldState = this.Saturation;
            this.bChangeSth = true;
            this.Saturation = value;
            this.sendToLight(true, function (error) {
                if (error) {
                    this.Saturation = oldState;
                    callback(error);
                }
            }.bind(this));
            callback();
        }


The last callback shouldn't be there. Maybe something like this will fix it

            this.log("setSaturation from/to:", this.Saturation, value);
            var oldState = this.Saturation;
            this.bChangeSth = true;
            this.Saturation = value;
            this.sendToLight(true, function (error) {
                if (error) {
                    this.Saturation = oldState;
                    callback(error);
                } else {
                    callback();
                }
            }.bind(this));
        }

Unfortunately I am away from home and cannot test it

**Comment by kounch** [comment]
Uploaded new version to npm and GitHub. Please check if your issue is resolved.

**Comment by kounch** [comment]
Tried the new version with a lot setSaturation messages and could not reproduce the problem anymore.

Closed.

**Comment by aphlor** [comment]
Thanks; Sorry, been on vacation - just updating and testing now.

**Comment by aphlor** [comment]
Rigorously tested and working perfectly! Thanks.
