### ISSUE TITLE
Error: Could not start scanning, state is unauthorized (not poweredOn)

### ISSUE THREAD

**Issue by bablat** [kounch/homebridge-avea-bulb#4]
Hello!

Thanks for taking the time to develop this plugin. I'm trying to use it, it seems that the OS sees the bulb on the BLE level, but there may be some bug in the code preventing the plugin from scanning.
I believe it may be this issue with initialization:
[https://github.com/sandeepmistry/noble/issues/228](url)

I don't have my dev box around, writing this issue report from my HTPC, so can't help with addressing this at the moment, perhaps next weekend. Hopefully this is a simple fix!

Here's my exception, it appears once I go to the home app on my iPhone or open the control center. I believe the accessory needs to be queried for state and the noble library fails:

    /usr/lib/node_modules/homebridge-avea-bulb/node_modules/noble/lib/noble.js:76
          throw error;
          ^

        Error: Could not start scanning, state is unauthorized (not poweredOn)
        at Noble.startScanning (/usr/lib/node_modules/homebridge-avea-bulb/node_modules/noble/lib/noble.js:71:17)
        at AveaBulbAccessory.getFromLight (/usr/lib/node_modules/homebridge-avea-bulb/index.js:285:23)
        at AveaBulbAccessory.getBrightness (/usr/lib/node_modules/homebridge-avea-bulb/index.js:353:14)
        at emitThree (events.js:116:13)
        at Characteristic.Brightness.emit (events.js:197:7)
        at Characteristic.Brightness.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
        at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:706:20)
        at Array.forEach (native)
        at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:670:8)
        at emitMany (events.js:127:13)
        at HAPServer.emit (events.js:204:7)
        at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
        at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
        at emitNone (events.js:86:13)
        at IncomingMessage.emit (events.js:188:7)
        at endReadableNT (_stream_readable.js:975:12)

**Comment by kounch** [comment]
Does the nodejs (homebridge) process has enough permissions to access Bluetooth?

If you are running it with a user with standard permissions and not root you must grant extra privileges as explained here (look into the “Running without root/sudo” section):

https://github.com/sandeepmistry/noble/blob/master/README.md

**Comment by bablat** [comment]
Thanks, that was indeed the issue.
For other people's reference, if you're not running as root run the following (for ubuntu based distros):

    sudo apt-get install libcap2-bin
and then
    sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

That should take care of it.
I'm almost done, homebridge runs and I am getting a `[Avea Bulb] Starting Noble scan..` in my log, but see nothing more and the device is unresponsive.
I'll try entering the bulb's details in directly instead of scanning, hope it helps.

**Comment by bablat** [comment]
This indeed got me a bit further, seems that the bulb is connected but the process still fails (homebridge doesn't crash though) and the bulb looks dead in iOS home app.

    [10/16/2017, 12:33:12 AM] [Kitchen] ScanStop received
    [10/16/2017, 12:33:12 AM] [Kitchen] Discovered: 7cec79d7b57b
    [10/16/2017, 12:33:12 AM] [Kitchen] UUID matches!
    (node:19888) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Connection Rejected due to Limited Resources (0xd)
    (node:19888) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Hope you can assist!

**Comment by kounch** [comment]
Is your bluetooth adapter one from Intel? There seems to ve a problem with these kind of adapters, as it is explained here: 

https://github.com/sandeepmistry/noble

I don't have one, so i cannot debug. Perhaps you can try to edit lines 109-110, and lines 118-119 of `index.js`, this way:

`this.bulb = new AveaBulb.Avea(this.perifSel);`
`this.bulb.connect();`

into

`Noble.stopScanning();`
`this.scanning = false;`
`this.bulb = new AveaBulb.Avea(this.perifSel);`
`this.bulb.connect();`

and see if that change solves the problem.

**Comment by bablat** [comment]
Yes, that was it. Thanks for your help.
Any chance for a permanent fix?

**Comment by kounch** [comment]
Will try to test that change with other adapters tonight. If it doesn't break anything, a new release this week will include it.

**Comment by kounch** [comment]
Uploaded release 1.0.3 including this fix.

Closed

**Comment by bablat** [comment]
Just wanted to close the loop and say everything works perfectly now, thanks for the work you put into developing and sharing this with us, and for your very prompt and professional handling of issues.
