### ISSUE TITLE
Possible EventEmitter memory leak detected / crash

### ISSUE THREAD

**Issue by JanJastrow** [kounch/homebridge-avea-bulb#8]
Hi there,
1) thank you for your plugin, it really makes homebridge shine (✌️)
2) lately I'm having problem with homebridge (it crashes after a couple of minutes) and I think it is related to you plugin

```
[…]
[2/25/2018, 9:10:25 PM] [Lampe 3] Lost bulb appears again!
[2/25/2018, 9:10:25 PM] [Lampe 1] Discovered: 78a50450bc85
[2/25/2018, 9:10:25 PM] [Lampe 1] This is not the bulb you are looking for
[2/25/2018, 9:10:25 PM] [Lampe 2] Discovered: 78a50450bc85
[2/25/2018, 9:10:25 PM] [Lampe 2] Lost bulb appears again!
[2/25/2018, 9:10:25 PM] [Lampe 3] Discovered: 78a50450bc85
[2/25/2018, 9:10:25 PM] [Lampe 3] This is not the bulb you are looking for
send hb to: 0x00000000036ee122
{"id":-1,"method":"get_prop","params":["power","bright","rgb"]}
[2/25/2018, 9:10:26 PM] [Lampe 1] Discovered: 78a50450bc85
[2/25/2018, 9:10:26 PM] [Lampe 1] This is not the bulb you are looking for
[2/25/2018, 9:10:26 PM] [Lampe 2] Discovered: 78a50450bc85
[2/25/2018, 9:10:26 PM] [Lampe 2] Lost bulb appears again!
[2/25/2018, 9:10:26 PM] [Lampe 3] Discovered: 78a50450bc85
[2/25/2018, 9:10:26 PM] [Lampe 3] This is not the bulb you are looking for
[2/25/2018, 9:10:27 PM] [Lampe 1] Discovered: 78a50450bc85
[2/25/2018, 9:10:27 PM] [Lampe 1] This is not the bulb you are looking for
[2/25/2018, 9:10:27 PM] [Lampe 2] Discovered: 78a50450bc85
[2/25/2018, 9:10:27 PM] [Lampe 2] Lost bulb appears again!
[2/25/2018, 9:10:27 PM] [Lampe 3] Discovered: 78a50450bc85
[2/25/2018, 9:10:27 PM] [Lampe 3] This is not the bulb you are looking for
(node:14485) Warning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
error:   failed to connect bulb=7cec79d773ff

/usr/local/lib/node_modules/homebridge-avea-bulb/lib/avea.js:41
                reject(err);
                       ^
ReferenceError: err is not defined
    at Timeout.setTimeout (/usr/local/lib/node_modules/homebridge-avea-bulb/lib/avea.js:41:24)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

As you can see, my homebridge log gets kinda spammed by your plugin until it finally crashed with the above error.
Do you have any idea what could cause this?

Setup:
- Linux/Debian/raspbian on an Pine A64 mini-pc
- homebridge-avea-bulb 1.1.1 (via npm)
- homebridge v0.4.32
- 3 avea bulbs

**Comment by burzka** [comment]
I have the same issue on Ubuntu.

**Comment by kounch** [comment]
It looks like you have Bluetooth connectivity problems, which span a lot of connection retries. Try to solve them and then see if it stops happening.

**Comment by kounch** [comment]
Closed for inactivity
